// tslint:disable
/**
 * WeatherForecast
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ComplexResponse,
    ComplexResponseFromJSON,
    ComplexResponseFromJSONTyped,
    ComplexResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface ComplexResponseControllerResponse
 */
export interface ComplexResponseControllerResponse {
    /**
     * 
     * @type {ComplexResponse}
     * @memberof ComplexResponseControllerResponse
     */
    data?: ComplexResponse;
    /**
     * 
     * @type {string}
     * @memberof ComplexResponseControllerResponse
     */
    error?: string;
}

export function ComplexResponseControllerResponseFromJSON(json: any): ComplexResponseControllerResponse {
    return ComplexResponseControllerResponseFromJSONTyped(json, false);
}

export function ComplexResponseControllerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexResponseControllerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ComplexResponseFromJSON(json['data']),
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function ComplexResponseControllerResponseToJSON(value?: ComplexResponseControllerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ComplexResponseToJSON(value.data),
        'error': value.error,
    };
}


