// tslint:disable
/**
 * Weather Forecast
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComplexResponse
 */
export interface ComplexResponse {
    /**
     * 
     * @type {string}
     * @memberof ComplexResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplexResponse
     */
    garbage?: string;
}

export function ComplexResponseFromJSON(json: any): ComplexResponse {
    return ComplexResponseFromJSONTyped(json, false);
}

export function ComplexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'garbage': !exists(json, 'garbage') ? undefined : json['garbage'],
    };
}

export function ComplexResponseToJSON(value?: ComplexResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'garbage': value.garbage,
    };
}


